"""
Central configuration for the brain-body bridge.

All neuron IDs, paths, and timing constants live here.
"""

from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class BridgeConfig:
    # Paths
    brain_repo_root: Path = Path(__file__).resolve().parent.parent.parent / "brain-model"
    data_dir: Path = Path(__file__).resolve().parent.parent / "data"

    # Brain timing
    brain_dt_ms: float = 20.0         # brain simulation window per step (was 10ms)
    brain_warmup_ms: float = 200.0    # initial brain warmup before loop
    body_steps_per_brain: int = 200   # body physics steps per brain step (match 20ms)

    # Encoding
    max_rate_hz: float = 100.0        # max Poisson rate for sensory input
    baseline_rate_hz: float = 10.0    # baseline rate when feature is zero

    # Decoder normalization
    rate_scale: float = 40.0          # Hz value that maps to tanh(1)

    # Brain model params
    w_syn: float = 0.275              # mV per synapse
    f_poi: float = 250                # Poisson weight scaling

    # Neuron population files (generated by scripts/select_populations.py)
    @property
    def sensory_ids_path(self) -> Path:
        return self.data_dir / "sensory_ids.npy"

    @property
    def readout_ids_path(self) -> Path:
        return self.data_dir / "readout_ids.npy"

    @property
    def decoder_groups_path(self) -> Path:
        return self.data_dir / "decoder_groups.json"

    @property
    def channel_map_path(self) -> Path:
        return self.data_dir / "channel_map.json"

    @property
    def completeness_path(self) -> Path:
        return self.brain_repo_root / "Completeness_783.csv"

    @property
    def connectivity_path(self) -> Path:
        return self.brain_repo_root / "Connectivity_783.parquet"
